### ISSUE TITLE
elixir.nvim blocks/lags after ':'

### ISSUE THREAD

**Issue by jinyeow** [awetzel/elixir.nvim#1]
Hello. I have an issue: Anytime I type ':' Neovim is either blocked or it lags. This only happens in elixir files i.e. when elixir.nvim completion is at work.

FYI I'm using deoplete. I tried changing the deoplete#delimiters global variable but that didn't seem to affect anything. Any idea why this happens or how I can fix this?

**Comment by awetzel** [comment]
Actually I am not using Deoplete, so the only thing I know is that when you are doing omnicompletion: 
CTRL-X CTRL-O, then the UI is blocked until you get autocompletion list. 
But if you are not, then nothing is done background (except with the autobuild option) so no reason to block anything.

If you use `let g:elixir_autobuild = 1`, it may cause issues when the build is too long, please let me know.

Did you try without deoplete ?

**Comment by jinyeow** [comment]
I haven't tried it without deoplete.I just tried to manually omnicomplete after typing `:` and it seems to be lagging since `:` returns a list of every possible module available including Erlang ones.

Also, the erlang modules tend to overwrite the `:` so for example instead of `:math` I get `math`. Looking in IEx, I realise that it's just what's returned if I try to tab complete a `:` in the IEx console.

I only noticed this being really annoying today when I was using a lot of symbols/erlang modules and I kept having to wait for the blocking to stop. I tried changing `self.min_pattern_length` in `rplugin/python3/deoplete/sources/elixir.py` from 1 to 2 and that seems to help. Again though, the completion list candidates for a `:` just overwrite the `:` which is somewhat annoying.

I was trying to find where the completion candidates were being gathered and maybe change it so that if the string to complete start's with a `:` then prepend the `:` to the candidate but I'm not sure where to find `ElixirComplete`.

Anyway, these were my findings. If you'd like I can submit a PR for the (very small) change I made so that the deoplete source doesn't end up blocking forever on `:`. Is there anyway to make the call non-blocking?

**Comment by awetzel** [comment]
OK I get it:
- first there is a bug when you complete erlang module with Multiple choices : with one choice, the `:` remains, with more, it disapears. So I will fix it ASAP
- second I have to disable completion for 0 letter module, which make IEx completion hangs.

The plugin source is in a separate repository, built with install.sh :
https://github.com/awetzel/nvim-rplugin/blob/master/lib/rplugin.ex#L70

**Comment by awetzel** [comment]
To update your plugin, just run install.sh again it will recompile the master version

**Comment by awetzel** [comment]
I didn't removed the `:` completion since it is useful with omnicompletion, is the behaviour of IEx shell  completion, and is not so slow on my machine. I think the good fix would be to change the self.min_pattern_length in the deoplete source.

**Comment by jinyeow** [comment]
The `:` completion works great now. I changed `self.min_pattern_length` to 2 and everything works smoothly now. Thanks!
