### ISSUE TITLE
Elixir.nvim with YouCompleteMe

### ISSUE THREAD

**Issue by johnhamelink** [awetzel/elixir.nvim#2]
Hey there,

First off, thanks for your work on this plugin! I've managed to get it to work great on my environment, with one small caveat:

I have `YouCompleteMe` installed using plug:

``` nvim
Plug 'Valloric/YouCompleteMe', { 'do': 'python ./install.py' }
```

If I have YCM installed alongside `elixir.nvim`, then every time `.` is pressed, nvim freezes for 2-3 seconds. Disabling YCM stops this. Is this a bug?

For now, I've modified my Plug line in my config to:

``` nvim
Plug 'Valloric/YouCompleteMe', { 'do': 'python ./install.py', 'for': ['ruby', 'eruby'] }
```

**Comment by awetzel** [comment]
Hey John,
Thanks for your interest ! 
My plugin does 2 things for completion: 
- use IEx completion function
- load asynchronously all modules in ROOTPROJ/_build/dev/*/ebin at start to allow completion withtout the need to load them dynamically. 

IEx completion from root ("" completion) need to browser all modules of the code server ( O(n) ), so if your project is big it can be really slow.

So 2 ideas for you : 
- augment 'g:ycm_min_num_of_chars_for_completion' only for elixir with a ftplugin/elixir.vim
- I will add ASAP an option to disable automatic module loading at start if you prefer dynamic module loading (so module completion will be incomplete for a module and will appears only after a function completion on the module), it may be relevant for big projects

**Comment by awetzel** [comment]
See https://github.com/awetzel/elixir.nvim/issues/4 to follow this issue, it gathers the other complains about this issue, I have added to the plugin some improvements to speed up the completion.
