### ISSUE TITLE
Omnicompletion results in "Unknown function: ElixirComplete"

### ISSUE THREAD

**Issue by linduxed** [awetzel/elixir.nvim#6]
I've followed the installation instructions and `<C-x><C-o>` reults in the error found in the title.

I also noticed when grepping through my plugins that it seems like there's nothing defining `ElixirComplete`, only code that tries to make use of that function.

Am I missing something?

**Comment by awetzel** [comment]
Maybe you forgot to run `:UpdateRemotePlugins` and restart vim.
Actually ElixirComplete is an Elixir function : https://github.com/awetzel/nvim-rplugin/blob/master/lib/rplugin.ex#L89-L137

The "host plugin" system of neovim is used to make the function available into neovim:
- `:UpdateRemotePlugins` scans plugins in `/configpath/rplugin/{LANGUAGE}/*`
- then launch the language specific host, here https://github.com/awetzel/neovim-elixir to "ask" which functions, commands and autocommands are implemented into the plugin
- the result is cached into the file "~/.config/nvim/.init.vim-rplugin~", typically it should contains for the my plugin : 

```
call remote#host#RegisterPlugin('elixir', '/Users/awetzel/.config/nvim/bundle/elixir.nvim/rplugin/elixir/nvim_rplugin-0.0.1.ez', [
      \ {'sync': 1, 'name': 'DocexGetBody', 'opts': {'eval': '[col(''.''),getline(''.''),expand(''%:p:h''),line(''.'')]'}, 'type': 'function'},
      \ {'sync': 1, 'name': 'ElixirComplete', 'opts': {'eval': '[col(''.''),getline(''.''),get(g:,''elixir_docpreview'',0),get(g:,''elixir_maxmenu'',70),expand(''%:p:h''),line(''.'')]'}, 'type': 'function'},
      \ {'sync': 1, 'name': 'ElixirExec', 'opts': {'bang': '', 'range': '%', 'eval': '[expand(''%:p:h'')]'}, 'type': 'command'},
      \ {'sync': 0, 'name': 'ElixirQuickBuild', 'opts': {'eval': '[line(''$''),expand(''%:p:h'')]'}, 'type': 'command'},
      \ {'sync': 0, 'name': 'MixLoad', 'opts': {'eval': '[expand(''%:p:h'')]'}, 'type': 'command'},
      \ {'sync': 0, 'name': 'MixStart', 'opts': {'nargs': '*'}, 'type': 'command'},
      \ {'sync': 0, 'name': 'MixStop', 'opts': {'nargs': '*'}, 'type': 'command'},
     \ ])
```

This Vimscript is executed at neovim launch, and make the named functions, commands and autocommands available with "autoload". When the function is called, a MSGPack RPC query is then made to the host plugin with a normalized message.

**Comment by alexlafroscia** [comment]
I was seeing this same issue, and running `:UpdateRemotePlugins` fixed the issue for me.  Deoplete was broken before, but that fixed it 👍
